package com.example.arifraza.pediatriccardiology;

import androidx.appcompat.app.AlertDialog;
import androidx.appcompat.app.AppCompatActivity;

import android.content.DialogInterface;
import android.content.Intent;
import android.os.Bundle;
import android.text.TextUtils;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.Toast;

import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.auth.FirebaseUser;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;

import java.util.Calendar;
import java.util.Date;

public class cmessage2 extends AppCompatActivity {
    DatabaseReference databaseReports;
    FirebaseAuth mAuth4;
    EditText editText7;
    EditText editText8;
    EditText editText11;
    Button button6;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_cmessage2);
        setTitle("Messaging a User");
        editText7 = (EditText) findViewById(R.id.editText7);
        editText8 = (EditText) findViewById(R.id.editText8);
        editText11 = (EditText) findViewById(R.id.editText11);

        button6 = (Button) findViewById(R.id.button6);
        final String value = getIntent().getExtras().getString("bucketno");

        databaseReports = FirebaseDatabase.getInstance().getReference("messages");

        mAuth4 = FirebaseAuth.getInstance();


        openr34();
        button6.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {

                openm(value);
                openml2(value);


            }
        });


    }


    public void openr34() {


       // final FirebaseUser user4 = mAuth4.getCurrentUser();
     //   editText7.setText(user4.getDisplayName().toString());
editText7.setText("Admin - MAM ACADEMY");


    }

    private void openm(final String value) {

        Date currentTime = Calendar.getInstance().getTime();
        String dat = currentTime.toString();

        String name = editText7.getText().toString().trim();
        String loc = editText8.getText().toString().trim();
        String con = editText11.getText().toString().trim();
        String mmsg2="(Not Answered yet)";
        String rnm2="(Not Answered yet)";
        String rml2=value;
        String dat2="(Not Answered yet)";

        final FirebaseUser user444 = mAuth4.getCurrentUser();
        String seml = "mamacademy786@gmail.com";

        String rdd= "New!";

        if (!TextUtils.isEmpty(name)&&!TextUtils.isEmpty(loc)&& !TextUtils.isEmpty(con)) {

            String id = databaseReports.push().getKey();

            //creating an Artist Object
            msg msg = new msg(id, name, con, loc,rdd,seml,mmsg2,rnm2,rml2,dat,dat2);

            //Saving the Artist
            databaseReports.child(id).setValue(msg);

            //setting edittext to blank again
            /*
            editText7.setText("");
            editText8.setText("");
            editText11.setText("");
*/

            //displaying a success toast
            Toast.makeText(this, "Message Sent", Toast.LENGTH_LONG).show();


        } else {
            /*

             */
            //if the value is not given displaying a toast
            Toast.makeText(this, "Please enter all info first", Toast.LENGTH_LONG).show();
        }


    }


    //email
    private void openml2(final String value){

        String messagel = "";
        messagel += "\n" +"MAM ACADEMY - Admin";
        messagel += "\n"+"-----------------------------------------------------" ;
        messagel += "\n" ;
        messagel += "\n" ;
        messagel += "\n" +  "From :"+ editText7.getText().toString();
        messagel += "\n" + " Subject :"+  editText11.getText().toString();
        messagel += "\n" + "Message :" +editText8.getText().toString();
        messagel += "\n" ;
        messagel += "\n" ;
        messagel += "\n" +"Message generated by the MAM Academy app";
        messagel += "\n" ;
        messagel += "\n" ;
        messagel += "\n"+"-----------------------------------------------------" ;
        messagel += "\n" ;
        messagel += "\n" +"MAM Academy";

       // String value = getIntent().getExtras().getString("bucketno");

        Intent intent = new Intent(Intent.ACTION_SEND);
        intent.putExtra(Intent.EXTRA_EMAIL,new String[] { value });

        intent.putExtra(Intent.EXTRA_SUBJECT, " MAM ACADEMY - ADMIN");
        intent.putExtra(Intent.EXTRA_TEXT, messagel);

        intent.setType("message/rfc822");

        intent.setPackage("com.google.android.gm");
        startActivity(intent);
        //for(int i=0;i<600;i++)

        runOnUiThread(new Runnable() {
            @Override
            public void run() {

                if (!isFinishing()){
                    new AlertDialog.Builder(cmessage2.this)
                            .setTitle("Message ")
                            .setMessage("Sent Successfully")
                            .setCancelable(false)
                            .setPositiveButton("ok", new DialogInterface.OnClickListener() {
                                @Override
                                public void onClick(DialogInterface dialog, int which) {
                                    // Whatever...
                                }
                            }).show();
                }
            }
        });

        editText7.setText("");
        editText8.setText("");
        editText11.setText("");



    }


}